name: youtrust_lt_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'
  flutter: '>=3.12.0-1.1.pre'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_shaders: ^0.1.2
  gap: ^3.0.1
  go_router: ^9.0.3
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  go_router_builder: ^2.2.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true
  shaders:
    - shaders/title.frag
